version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masterdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/masterdb"
      MONGODB_URL: "mongodb://mongodb:27017/"
      UPLOAD_FOLDER: "/data/uploads"
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/data/uploads

volumes:
  pgdata:
  mongo_data: