version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-masterdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masterdb
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: mongo-tenants
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: pdf-microservice
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masterdb
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      OPENAI_API_KEY: your-openai-key
    depends_on:
      - postgres
      - mongo